# Generated by Django 5.2.3 on 2025-06-18 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_category_product_product_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
